declare var chrome: any;
declare var mpEZTrack: any;
declare var ALTERED_MIXPANEL_DATA: any;
declare var mixpanel: any;
declare var Papa: any;
declare var saveFile: any;
declare var MIXPANEL_CATCH_FETCH_ACTIVE: boolean;
declare var CATCH_FETCH_INTENT: string;
declare var SESSION_REPLAY_ACTIVE: boolean;
// declare var APP: object;
