declare var chrome: any;
declare var ALTERED_MIXPANEL_DATA: any;
declare var ALTERED_MIXPANEL_OVERRIDES: any;
declare var mixpanel: any;
declare var Papa: any;
declare var saveAs: any;
declare var MIXPANEL_CATCH_FETCH_ACTIVE: boolean;
declare var CATCH_FETCH_INTENT: string;
declare var SESSION_REPLAY_ACTIVE: boolean;
declare var MIXPANEL_WAS_INJECTED: boolean;
// declare var APP: object;
